### ISSUE TITLE
Change of username

### ISSUE THREAD

**Issue by Canoeboy** [stoo2000/membermap#26]
User has name A on the member map

When they change their username (to B for instance) - the map doesnt update and still shows A - it still shows the old username but still links to the correct new username profile

**Comment by MartinAronsen** [comment]
It should fix itself on the next recache. 
I'll make sure that is done after a profile update in the next release.

**Comment by Canoeboy** [comment]
Its still showing as my old member name

Have rebuilt caches - updated to 3.1.5 and reset my location

Still shows as my old username
